apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: nju21
  labels:
    app: application
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8998"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
    spec:
      hostname: application
      containers:
        - name: application
          image: harbor.edu.cn/nju21/application:{VERSION}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: nju21
  labels:
    app: application
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
    - name: tcp
      protocol: TCP
      port: 8998
      targetPort: 8998
  selector:
    app: application